title: Kabar Tenggarong
tagline: Berita Kukar Paling Update
description: Portal berita Tenggarong dan Kutai Kartanegara
url: '' # kosongin dulu

author:
  name: Mas Djoem
  email: email-lo@gmail.com

permalink: /:title/   # Wajib biar link cantik

social:
  name: Kabar Tenggarong
  links:
    - https://instagram.com/kabartenggarong
